const SUCCESS_RESPONSE = 2010

const ERROR_USER_NAME_EXIST = 5020
const USER_NAME_NOT_FOUND = 5021

const PARAM_ERROR = 5010
const TO_MANY_REQUESTS = 5011
const REFRESH_TOKEN_AUTH_FAILED = 5097
const AUTH_FAILED = 5098
const ERROR_INTERNAL = 5099

module.exports = {
  SUCCESS_RESPONSE,
  TO_MANY_REQUESTS,
  PARAM_ERROR,
  USER_NAME_NOT_FOUND,
  ERROR_USER_NAME_EXIST,
  AUTH_FAILED,
  REFRESH_TOKEN_AUTH_FAILED,
  ERROR_INTERNAL,
}
